# -*- coding: utf-8 -*-
"""Churn Analysis & Predictive Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H616CJr6knvzYuIsTpFJHOuUcejatqU1

# Import Libraries & Load Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv")
df.head()

"""# Data Cleaning"""

# handling missing values
df.replace(" ", np.nan, inplace=True)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.dropna(inplace=True)

# Dropping Customer ID
df.drop(['customerID'], axis=1, inplace=True)

"""# Exploratory Data Analysis (EDA)"""

# Churn Distributin
sns.countplot(x='Churn', data=df)
plt.title("Churn Distribution")

# Churn Vs Contract
sns.countplot(x='Contract', hue='Churn', data=df)
plt.xticks(rotation=0)
plt.title("Contract Type vs Churn")

# Churn Vs Tenure
sns.histplot(data=df, x='tenure', hue='Churn', kde=True)
plt.title("Tenure Distribution by Churn")

# Churn Vs Monthly Charges
sns.boxplot(y='MonthlyCharges', x='Churn', data=df)

"""# Feature Encoding + Scaling"""

# Label Encoding for yes/no columns:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])

# Train-test split
from sklearn.model_selection import train_test_split

X = df.drop('Churn', axis=1)
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

feat_imp = pd.DataFrame({'feature': X.columns, 'importance': rf.feature_importances_})
feat_imp = feat_imp.sort_values('importance', ascending=False).reset_index(drop=True)
feat_imp.head(15)

"""# ML Model Training"""

from sklearn.linear_model import LogisticRegression

# Logistic Regression Model
lr = LogisticRegression(max_iter=2000, random_state=42)
lr.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

from sklearn.ensemble import RandomForestClassifier

# Random Forest Model
rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)

print("Random Forest model trained successfully.")

from xgboost import XGBClassifier

# XGBoost Model
xgb = XGBClassifier(
    max_depth=6,
    learning_rate=0.1,
    n_estimators=300,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

print("XGBoost model trained successfully.")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report
import matplotlib.pyplot as plt

models = {
    "Logistic Regression": lr,
    "Random Forest": rf,
    "XGBoost": xgb
}

for model_name, model in models.items():
    plt.figure()
    y_pred = model.predict(X_test)

    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot()
    plt.title(f"Confusion Matrix - {model_name}")
    plt.show()

    print(f"\n----- {model_name} Classification Report -----\n")
    print(classification_report(y_test, y_pred))

"""# Model Evaluation"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def evaluate(model):
    pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, pred))
    print(classification_report(y_test, pred))

evaluate(lr)
evaluate(rf)
evaluate(xgb)

"""# Explainable AI with SHAP"""

import shap
shap.initjs()

explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test)

df_results = X_test.copy()
df_results['Churn_Prob'] = xgb.predict_proba(X_test)[:,1]

df_results['Risk_Segment'] = pd.cut(
    df_results['Churn_Prob'],
    bins=[0, 0.3, 0.6, 1],
    labels=['Low Risk', 'Medium Risk', 'High Risk']
)

"""# Customer Segmentation (High, Medium, Low Churn Risk)"""

sns.countplot(x=df_results['Risk_Segment'])
plt.title("Customer Risk Segments")

"""# Matplotlib Dashboard"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("seaborn-v0_8")

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle("Customer Churn Insights Dashboard", fontsize=18, fontweight='bold')


# Churn Distribution

sns.countplot(ax=axes[0,0], x=df['Churn'], palette="Set2")
axes[0,0].set_title("Churn Distribution", fontsize=14)
axes[0,0].set_xlabel("Churn")
axes[0,0].set_ylabel("Count")


# Contract Type vs Churn

sns.countplot(ax=axes[0,1], data=df, x='Contract', hue='Churn', palette="Set1")
axes[0,1].set_title("Contract Type vs Churn", fontsize=14)
axes[0,1].set_xlabel("Contract Type")
axes[0,1].tick_params(axis='x', rotation=15)


# Tenure Distribution by Churn

sns.histplot(ax=axes[0,2], data=df, x='tenure', hue='Churn', kde=True, palette="dark")
axes[0,2].set_title("Tenure Distribution by Churn", fontsize=14)
axes[0,2].set_xlabel("Customer Tenure")


# Monthly Charges vs Churn (Boxplot)

sns.boxplot(ax=axes[1,0], data=df, y='MonthlyCharges', x='Churn', palette="coolwarm")
axes[1,0].set_title("Monthly Charges by Churn", fontsize=14)
axes[1,0].set_xlabel("Churn")
axes[1,0].set_ylabel("Monthly Charges")


# Risk Segments (High / Medium / Low)

sns.countplot(ax=axes[1,1], x=df_results['Risk_Segment'], palette="viridis")
axes[1,1].set_title("Customer Risk Segmentation", fontsize=14)
axes[1,1].set_xlabel("Risk Segment")
axes[1,1].set_ylabel("Count")



axes[1,2].axis('off')

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()